# Uncomment the next line to define a global platform for your project
platform :ios, '13.7'

target 'desafio-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '6.0.0-rc.1'
  pod 'RxCocoa', '6.0.0-rc.1'
  # Pods for desafio-ios
end

target 'desafio-iosTests' do
  inherit! :search_paths
  pod 'RxBlocking', '6.0.0-rc.1'
  pod 'RxTest', '6.0.0-rc.1'
  # Pods for testing
end

target 'desafio-iosUITests' do
  # Pods for testing
end